# Generated by Django 4.2 on 2023-04-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
